# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAE',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(max_length=100, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('cae', models.TextField(max_length=100, null=True)),
                ('state', models.TextField(max_length=100, null=True)),
                ('city', models.TextField(max_length=100, null=True)),
                ('started_at', models.TextField(max_length=100, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('address_l2', models.TextField(max_length=500, null=True)),
                ('phone', models.TextField(max_length=100, null=True)),
                ('mobile', models.TextField(max_length=100, null=True)),
                ('fax', models.TextField(max_length=100, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('info', models.BooleanField(default=False)),
                ('about', models.TextField(max_length=10000, null=True)),
                ('products', models.TextField(max_length=10000, null=True)),
                ('brands', models.TextField(max_length=5000, null=True)),
                ('tags', models.TextField(max_length=10000, null=True)),
                ('links', models.BooleanField(default=False)),
                ('website', models.TextField(max_length=100, null=True)),
                ('facebook', models.TextField(max_length=100, null=True)),
                ('twitter', models.TextField(max_length=100, null=True)),
                ('linkedin', models.TextField(max_length=100, null=True)),
                ('googleplus', models.TextField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('active_tab', models.IntegerField(default=1)),
                ('already_crawled', models.BooleanField(default=False)),
                ('error_crawling', models.BooleanField(default=False)),
                ('visits_users', models.IntegerField(default=0)),
                ('visits_bots', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.TextField(max_length=32, primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Companies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
