# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_visits_companiescrawled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.TextField(max_length=10)),
                ('company', models.TextField(max_length=50, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('ip', models.GenericIPAddressField()),
                ('useragent', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
